### ISSUE TITLE
As someone who does not want to make an account, I want to join or create a game so that I can access a game lobby.

### ISSUE THREAD

**Issue by MaeveRositzke** [samarthjj/CSE-442-Group-Project#16]
**Acceptance Tests**

*Test 1* Confirm profile is functional.
1) Navigate to http://minorprophets.tech/creategame.
2) Click "Continue as Guest"
3) Click "Profile" (in the upper left corner).
4) See that profile still works for guests. The statistics are still shown. Click "Back."
5) Click "Logout" in the upper right corner.

*Test 2* Confirm guests can start a new game.
1) Navigate to http://minorprophets.tech/creategame.
2) Click "Continue as Guest"
3) Click "Start New Game"
4) See a single username in the table labeled "Players." This is the username given to your guest account.
5) Click "Cancel" in the upper right corner.
6) Click "Logout" in the upper right corner.

*Test 3* Confirm guests can join an existing game.
1) Navigate to http://minorprophets.tech/creategame.
2) Login with your login credentials or use the following credentials: Username: `zenhub1` Password: `Apple123*`. Click "Login."
3) Click "Start New Game"
   3a) Have another user follow these steps on a different device:
   i) Navigate to http://minorprophets.tech/creategame.
   ii) Click "Continue as Guest"
   v) Enter the code displayed in the upper left corner of the game room host's screen in the text box "Enter code here"
   vi) Click "Join Game"
   vii) See two usernames in the table labeled "Players." One is the host of the room, the other is your guest username.
4) [Player who created the game] Click "Cancel" in the upper right corner. [Player who joined the game] Click the back button of the browser.
5) [Both Users] Click "Logout" in the upper right corner.

*Test 4* Confirm guests can start a new game and that another guest can join that game.
1) Navigate to http://minorprophets.tech/creategame.
2) Click "Continue as Guest"
3) Click "Start New Game"
   3a) Have another user follow these steps on a different device:
   i) Navigate to http://minorprophets.tech/creategame.
   ii) Click "Continue as Guest"
   v) Enter the code displayed in the upper left corner of the game room host's screen in the text box "Enter code here"
   vi) Click "Join Game"
   vii) See two usernames in the table labeled "Players." Both guest usernames should appear here.
5) [Player who created the game] Click "Cancel" in the upper right corner. [Player who joined the game] Click the back button of the browser.
6) [Both users] Click "Logout" in the upper right corner.

*Test 5* Confirm guests can start a new game and that a player with an account can join the game.
1) Navigate to http://minorprophets.tech/creategame.
2) Click "Continue as Guest"
3) Click "Start New Game"
   3a) Have another user follow these steps on a different device:
   i) Navigate to http://minorprophets.tech/creategame.
   ii) Login with the credentials: Username: `zenhub1` Password: `Apple123*`. Click "Login"
   v) Enter the code displayed in the upper left corner of the game room host's screen in the text box "Enter code here"
   vi) Click "Join Game"
   vii) See two usernames in the table labeled "Players." Both the guest host and player account username appear here.
5) [Player who created the game] Click "Cancel" in the upper right corner. [Player who joined the game] Click the back button of the browser.
6) [Both users] Click "Logout" in the upper right corner.

**Comment by ProfMatthewHz** [comment]
(As written now, this should _probably_ be two different features:  
* joining an existing game 
* creating a new game
these really are different features and I can see worlds where we want to force people to have accounts to create a game. Not a big deal at this point.
