### ISSUE TITLE
Set up Figma

### ISSUE THREAD

**Issue by joebalb** [samarthjj/CSE-442-Group-Project#19]
**Acceptance Tests**

*Test 1*
1) Each member of the team logs in to/makes a Figma account
2) Each member ensures they have access to the "Minor Prophets" project
3) Each member ensures they can view and edit the "Team project" file

*Test 2*
1) Log into Figma
2) Open "Team projects" file
3) Click on   in the "Intitial" frame
4) Confirm this leads you to

**Comment by MaeveRositzke** [comment]
Link to Figma: https://www.figma.com/file/0Ilc459zevacYxPHoQc6Ed/Music-Game?node-id=16%3A38

Links to websites used for help: https://uxplanet.org/figma-all-you-need-to-know-156b52b88e54
