### ISSUE TITLE
As someone who is playing with friends, I want to send a message so that I see my messages in the messages space.

### ISSUE THREAD

**Issue by MaeveRositzke** [samarthjj/CSE-442-Group-Project#3]
**Acceptance Tests**

*Test 1 - Text Messages/Emojis*
1) Go to http://minorprophets.tech/ 
2) Login using the username `zenhub1`.
3) Enter `Apple123*` as the Password.
4) Click the "Start New Game" button.
5) Click the "Start Game" button.
6) Type in a message of your choice, comprising on emoticons, which can be chosen by clicking on the smiley face on the right side of the input.
7) Hit the "Enter" button on your keyboard.
8) Confirm that your message, with emojis, was sent and appears in the Messages.

---

*Test 2 - 👍*
<ol>
<li>Go to http://minorprophets.tech/ </li>
<li>Login using the username `zenhub1`.</li>
<li>Enter `Apple123*` as the Password.</li>
<li>Click the "Login" button.</li>
<li>Click the "Start New Game" button.</li>
<li>Click the "Start Game" button.</li>
<li>Confirm that you see quick reaction for "👍".</li>
<li>Confirm that upon clicking the quick reaction for 👍, a message is sent on your behalf with the structure, "zenhub1: 👍" and appears in the Messages.</li>
</ol>

---

*Test 3 - 👎*
<ol>
<li>Go to http://minorprophets.tech/ </li>
<li>Login using the username `zenhub1`.</li>
<li>Enter `Apple123*` as the Password.</li>
<li>Click the "Login" button.</li>
<li>Click the "Start New Game" button.</li>
<li>Click the "Start Game" button.</li>
<li>Confirm that you see quick reaction for "👎".</li>
<li>Confirm that upon clicking the quick reaction for 👎, a message is sent on your behalf with the structure, "zenhub1: 👎" and appears in the Messages.</li>
</ol>

---

*Test 4 - 👏*
<ol>
<li>Go to http://minorprophets.tech/ </li>
<li>Login using the username `zenhub1`.</li>
<li>Enter `Apple123*` as the Password.</li>
<li>Click the "Login" button.</li>
<li>Click the "Start New Game" button.</li>
<li>Click the "Start Game" button.</li>
<li>Confirm that you see quick reaction for "👏".</li>
<li>Confirm that upon clicking the quick reaction for 👏, a message is sent on your behalf with the structure, "zenhub1: 👏" and appears in the Messages.</li>
</ol>

**Comment by ProfMatthewHz** [comment]
The action in this story, "I want there to be a messaging service" is not something the user does. This could be selecting a quick action (those are actions the user can choose) or it could be typing in a message (ditto). The observable outcome is what visual indicator does the **sender** receive when the message is sent. (The update received by the other user is a side effect.)

This user story suggests messages are sent between friends; how do I select which friend I am sending a message to? If this is being sent to all of the players (including the sender, which means this will also handle the receiving of messages), make certain this is clear.

As for the tests, **be specific as to what the user should do and what they will see in response**. How would an untrained user do any of the following:
  - "Confirm that upon clicking one of the quick reactions, a message is sent on your behalf with the structure"
   - "Confirm that you are able to send a text message"
   - "Confirm that you are able to send a message comprising of emojis and plain text"

**Comment by ProfMatthewHz** [comment]
What is the _observable outcome_ for the user who SENDS the message to someone? That needs to be in this story.
