### ISSUE TITLE
Create 30-second timer to synchronously maintain game-pace for multiple players in the question screens.

### ISSUE THREAD

**Issue by HarrisonHutton** [samarthjj/CSE-442-Group-Project#54]
**Task Tests**

*Test 1* **(Timer gets to 0 before moving on)**
1) Start the app locally to load the main page
2) Login with the username: **`zenhub3`** and password: **`Apple123*`** (Call this account *Player A*)
3) Click "Start New Game"
4) In a new tab, start the app locally to load the main page
5) Login with the username: **`zenhub2`** and password: **`Apple123*`** (Call this account *Player B*)
6) Using the displayed game code on Player A's screen, join the game related to this code on Player B's screen by entering the game code in the only textbox on the screen and then pressing "Join Game"
7) In the next screen, on Player A's game, ignore the genre selection buttons and press "Start Game"
8) For both players, in the top-right of this new screen (this will have a question prompt on it; call this page the "question screen"), verify that the clock is ticking down 1 second at a time
9) Verify that the timer stops counting down once it reaches 0 by seeing the number 0 in the timer box for more than 1 second.

*Test 2* **(Timer doesn't reach 0 -> Lie and press "Countdown Done" on one player's game without loss of generality)**
1) Start the app locally to load the main page
2) Login with the username: **`zenhub3`** and password: **`Apple123*`** (Call this account *Player A*)
3) Click "Start New Game"
4) In a new tab, start the app locally to load the main page
5) Login with the username: **`zenhub2`** and password: **`Apple123*`** (Call this account *Player B*)
6) Using the displayed game code on Player A's screen, join the game related to this code on Player B's screen by entering the game code in the only textbox on the screen and then pressing "Join Game"
7) In the next screen, on Player A's game, ignore the genre selection buttons and press "Start Game"
8) For both players, in the top-right of this new screen (this will have a question prompt on it; call this page the "question screen"), verify that the clock is ticking down 1 second at a time
9) Before the timer reaches 0, click "Countdown Done" on Player A's screen
10) If Player A's game is directed to the screen that holds the answer to the previous question, then the timer counts down correctly and it doesn't cause problems if it doesn't reach 0 seconds remaining.
11) Player B should be able to finish his/her round (by selecting one answer box and waiting for the time to count down to 0) without any interruption

*Test 3* **(Timer doesn't reach 0 -> One player quits early)**
1) Start the app locally to load the main page
2) Login with the username: **`zenhub3`** and password: **`Apple123*`** (Call this account *Player A*)
3) Click "Start New Game"
4) In a new tab, start the app locally to load the main page
5) Login with the username: **`zenhub2`** and password: **`Apple123*`** (Call this account *Player B*)
6) Using the displayed game code on Player A's screen, join the game related to this code on Player B's screen by entering the game code in the only textbox on the screen and then pressing "Join Game"
7) In the next screen, on Player A's game, ignore the genre selection buttons and press "Start Game"
8) For both players, in the top-right of this new screen (this will have a question prompt on it; call this page the "question screen"), verify that the clock is ticking down 1 second at a time
9) Before the clock hits 0, click the "Quit" button on Player A's screen
10) If Player A's game is directed to the main screen that has the "Join Game" and "Start New Game" buttons, then the timer counts down correctly and it doesn't cause problems if it doesn't reach 0 seconds remaining.

*Test 4* **(Timer doesn't reach 0 -> All players quit early)**
1) Start the app locally to load the main page
2) Login with the username: **`zenhub3`** and password: **`Apple123*`** (Call this account *Player A*)
3) Click "Start New Game"
4) In a new tab, start the app locally to load the main page
5) Login with the username: **`zenhub2`** and password: **`Apple123*`** (Call this account *Player B*)
6) Using the displayed game code on Player A's screen, join the game related to this code on Player B's screen by entering the game code in the only textbox on the screen and then pressing "Join Game"
7) In the next screen, on Player A's game, ignore the genre selection buttons and press "Start Game"
8) For both players, in the top-right of this new screen (this will have a question prompt on it; call this page the "question screen"), verify that the clock is ticking down 1 second at a time
9) Before the clock hits 0, click the "Quit" button on both Player A's and Player B's screen
10) If both Player A's and Player B's games are directed to the main screen that has the "Join Game" and "Start New Game" buttons, then the timer counts down correctly and it doesn't cause problems if it doesn't reach 0 seconds remaining.

**Comment by ProfMatthewHz** [comment]
Not sure what the UNRELEASED... in the title is for -- since only issues marked CLOSED are merged to DEV (and MAIN), that is clear from the pipeline.

For your tests: is there a difference in user accounts? If so, write this up as 3 different tests. If not, just write the tet using one of the user names. I probably have other changes I will want to see (aren't you already happy to have me?) but will need to understand the system more before asking them.

**Comment by ProfMatthewHz** [comment]
What is the point of the countdown done button? How can a test fail when the last step is: "11) the consequences for the other player are currently left undefined"? If the test cannot fail, why bother with it?

**Comment by ProfMatthewHz** [comment]
"11) The consequences for the other player are currently left undefined" is not a valid test step since it, by definition, cannot fail.
