### ISSUE TITLE
Add ability for users to play as a guest (with a temporary account)

### ISSUE THREAD

**Issue by joebalb** [samarthjj/CSE-442-Group-Project#56]
**Task Tests**

*Test 1* Confirm profile is functional.
1) Run app.py and npm start on local machine. Open webpage.
2) Click "Continue as Guest"
3) Click "Profile" (in the upper left corner).
4) See that profile still works for guests. The statistics are still shown. Click "Back."
5) Click "Logout" in the upper right corner.

*Test 2*
1) Run app.py and npm start on local machine. Open webpage.
2) Click "Continue as Guest"
3) Click "Start New Game". See a single username in the table labeled "Players." This is the username given to your guest account.
4) Choose 1 under "Number of Rounds." Click "Start Game"
5) Choose an answer to the given question. Click one of the answers to choose.
6) Click "Countdown Done" [If the timer is implemented, allow the timer to run out.].
7) Click "Reveal Answer"
8) Click "Calculate Scores"
9) Click "Get Scores"
10) Confirm that if you got the answer right, your score was incremented.
11) Click "New Question"
12) Repeat steps 7-13 until the question displayed has the text "Game Over."
13) Press "New Question" again.
14) Press "Game Over" to see scores.
15) Press "Exit"

*Test 3*
1) Run app.py and npm start on local machine. Open webpage.
2) Click "Continue as Guest"
3) Click "Start New Game" See a single username in the table labeled "Players." This is the username given to your guest account.
   3a) Have another user follow these steps:
   i) Navigate to http://minorprophets.tech/creategame on a different device than the room host.
   ii) Login using the following credentials: Username: `zenhub1` Password: `Apple123*`
   iii) Enter the code displayed in the upper left corner of the game room host's screen in the text box "Enter code here"
   iv) Click "Join Game"
4) [User who created the game] Choose 1 under "Number of Rounds." Click "Start Game".
5) [Both users] Choose an answer to the given question. Click one of the answers to choose.
6) [Both users] Click "Countdown Done" [If the timer is implemented, allow the timer to run out.]
7) [User who created the game] Click "Reveal Answer"
8) [User who created the game] Click "Calculate Scores"
9) [Both users] Click "Get Scores"
10) [Both users] Confirm that if you got the answer right, your score was incremented.
11) [Both users] Click "New Question"
12) Repeat steps 7-13 until the question displayed has the text "Game Over."
13) [Both users] Press "New Question" again.
14) [Both users] Press "Game Over" to see scores.
15) [Both users] Press "Exit"

*Test 4*
1) Run app.py and npm start on local machine. Open webpage.
2) Login using the following credentials: Username: `zenhub1` Password: `Apple123*`
3) Click "Start New Game"
   3a) Have another user follow these steps:
   i) Navigate to http://minorprophets.tech/creategame on a different device than the room host.
   ii) Click "Continue as Guest"
   iii) Enter the code displayed in the upper left corner of the game room host's screen in the text box "Enter code here"
   iv) Click "Join Game". See two usernames in the table labeled "Players." One is `zenhub1`, the other is your guest username.
4) [User who created the game] Choose 1 under "Number of Rounds." Click "Start Game"
5) [Both users] Choose an answer to the given question. Click one of the answers to choose.
6) [Both users] Click "Countdown Done" [If the timer is implemented, allow the timer to run out.]
8) [User who created the game] Click "Reveal Answer"
9) [User who created the game] Click "Calculate Scores"
10) [Both users] Click "Get Scores"
11) [Both users] Confirm that if you got the answer right, your score was incremented.
12) [Both users] Click "New Question"
13) Repeat steps 7-13 until the question displayed has the text "Game Over."
14) [Both users] Press "New Question" again.
15) [Both users] Press "Game Over" to see scores.
16) [Both users] Press "Exit"

*Test 5*
1) Run app.py and npm start on local machine. Open webpage.
2) Have 2 users click "Continue as Guest" on different devices.
3) User A: Click "Start New Game."
4) User B: Enter the code displayed in the upper left corner of the game room host's screen in the text box "Enter code here"
5) User B: Click "Join Game"
6) User A: Choose 1 under "Number of Rounds." Click "Start Game"
7) [Both users] Choose an answer to the given question. Click one of the answers to choose.
8) [Both users] Click "Countdown Done" [If the timer is implemented, allow the timer to run out.]
9) User A: Click "Reveal Answer"
10) User A: Click "Calculate Scores"
11) [Both users] Click "Get Scores"
12) [Both users] Confirm that if you got the answer right, your score was incremented.
13) [Both users] Click "New Question"
14) Repeat steps 7-13 until the question displayed has the text "Game Over."
15) [Both users] Press "New Question" again.
16) [Both users] Press "Game Over" to see scores.
17) [Both users] Press "Exit"

**Comment by ProfMatthewHz** [comment]
(See my comments on the acceptance test for how these tests should be revised. Remember that specifics as to number of rounds, etc. are important here, too.)

There is actually a lot of different actions going on here at the front-end and database layers. In the real-world we would want to split this into at least 2 tasks: one describing what the functions are in the front-end and another about how this gets communicated to the database. These tests may convince me that the code works, but they do NOTHING for debugging. Finer-grained tasks make writing meaningful tests easier and that makes coding and debugging simpler. Remember: hours of coding makes up for minutes of planning.
