### ISSUE TITLE
Add ability for room owner to select number of rounds

### ISSUE THREAD

**Issue by MaeveRositzke** [samarthjj/CSE-442-Group-Project#58]
**Task Tests**

Test 1 (every button)
1) Go to http://minorprophets.tech/ or run the app locally
2) Use username: "zenhub1" and  password: "Apple123\*" as login credentials
3) Click "Login"
4) Click "Start New Game"
5) Confirm that you see 5 buttons to select for the number of rounds: 1, 2, 3, 4, and 5
6) In this step, select one of the buttons, the first time, select "1", then the next time "2" and so on, until all buttons have been tested
7) Confirm that the button you selected is highlighted
8) Click "Start Game"
9) Confirm that the question screen says Round 1 out of however many rounds you selected in Step 6 in the element with id "rounds"
10) Select an answer and press "Countdown Done"
11) Confirm that the answer screen says Round 1 out of however many rounds you selected in Step 6  in the element with id "rounds"
12) Look at the Python terminal for the printed rooms_user_info dictionary and confirm that "current_round" is 1, "rounds" is the number of rounds from step 6, and "round_counter" is 1
13) Click "Quit"
14) Repeat steps 5-13 4 more times, choosing a new round button each time

*Test 2* (current round updates correctly)
1) Go to http://minorprophets.tech/ or run the app locally
2) Use username: "zenhub1" and  password: "Apple123\*" as login credentials
3) Click "Login"
4) Click "Start New Game"
5) Select "3" for the number of rounds
6) Confirm that the "3" button is highlighted
7) Click "Start Game"
8) Confirm that the question screen says Round 1 out of 3 in the element with id "rounds"
9) Select an answer and press "Countdown Done"
10) Confirm that the answer screen says Round 1 out of 3 in the element with id "rounds"
11) Look at the Python terminal for the printed rooms_user_info dictionary and confirm that "current_round" is 1, "rounds" is 3, and "round_counter" is what question you are on within the current round (1, 2, or 3)
12) Click "Reveal Answer"
13) Click "New Question"
14) Repeat steps 8-13 2 more times
15) Confirm that the question screen says Round 2 out of 3 in the element with id "rounds"
16) Select an answer and press "Countdown Done"
17) Confirm that the answer screen says Round 2 out of 3 in the element with id "rounds"
18) Look at the Python terminal for the printed rooms_user_info dictionary and confirm that "current_round" is 2, "rounds" is 3, and "round_counter" is what question you are on within the current round (1, 2, or 3)
19) Click "Reveal Answer"
20) Click "New Question"
21) Repeat steps 15-20 2 more times
22) Confirm that the question screen says Round 3 out of 3 in the element with id "rounds"
23) Select an answer and press "Countdown Done"
24) Confirm that the answer screen says Round 3 out of 3 in the element with id "rounds"
25) Look at the Python terminal for the printed rooms_user_info dictionary and confirm that "current_round" is 3, "rounds" is 3, and "round_counter" is 1

*Test 3* (change your mind about the number of rounds)
1) Go to http://minorprophets.tech/ or run the app locally
2) Use username: "zenhub1" and  password: "Apple123\*" as login credentials
3) Click "Login"
4) Click "Start New Game"
5) Select "2" for the number of rounds 
6) Select "4" for the number of rounds
7) Confirm that the "4" button is highlighted
8) Click "Start Game"
9) Confirm that the question screen says Round 1 out of 4 in the element with id "rounds"
10) Select an answer and press "Countdown Done"
11) Confirm that the answer screen says Round 1 out of 4 in the element with id "rounds"
12) Look at the Python terminal for the printed rooms_user_info dictionary and confirm that "current_round" is 1, "rounds" is 4, and "round_counter" is 1

*Test 4* (test with 2 users)
1) Go to http://minorprophets.tech/ or run the app locally
2) Use username: "zenhub1" and  password: "Apple123\*" as login credentials
3) Click "Login"
4) Click "Start New Game"
5) Select 5 for the number of rounds
6) Go to http://minorprophets.tech/ in a different browser to simulate a second player
7) Use username: "zenhub2" and  password: "Apple123\*" as login credentials
8) Click "Login"
9) Enter the roomcode
10) Click "Join Game"
11) Wait for room owner to start the game
12) Click "Start Game" in the _first_ browser
13) In the _second_ browser, confirm that the question screen says Round 1 out of 5 in the element with id "rounds"
14) Select an answer and press "Countdown Done" on _both_ browsers
15) In the _second_ browser, confirm that the answer screen says Round 1 out of 5 in the element with id "rounds"

*Test 5* (initially does not choose a number of rounds, then does)
1) Go to http://minorprophets.tech/
2) Use username: "zenhub1" and password: "Apple123\*" as login credentials
3) Click "Login"
4) Click "Start New Game"
5) Do not select the number of rounds
6) Confirm that none of the round number choices are highlighted
7) Click "Start Game"
8) Confirm that you do not go to the 1st question screen
9) Confirm that you see an alert box displayed as a result of calling the alert() function telling you to pick a round number and click "OK"
10) Select "4" for the number of rounds
11) Click "Start Game" again
12) Confirm that you now go to the question screen, and that it says Round 1 out of 4 in the element with id "rounds"
13) Look at the Python terminal for the printed rooms_user_info dictionary and confirm that "current_round" is 1, "rounds" is 4, and "round_counter" is 1

*Test 6* (added test that addresses the rare race, basically just abuse the app to try to get it to break)
1) Go to http://minorprophets.tech/ or run the app locally
2) Use username: "zenhub1" and  password: "Apple123\*" as login credentials
3) Click "Login"
4) Click "Start New Game"
5) Click "Start Game"
6) Confirm that you do not go to the 1st question screen
7) Confirm that you see an alert box displayed as a result of calling the alert() function telling you to pick a round number and click "OK"
8) Click "Start Game"
9) Confirm that you do not go to the 1st question screen
10) Confirm that you see an alert box displayed as a result of calling the alert() function telling you to pick a round number and click "OK"
11) Go to http://minorprophets.tech/ in a different browser to simulate a second player
12) Use username: "zenhub2" and  password: "Apple123\*" as login credentials
13) Click "Login"
14) Enter roomcode and click "Join Game"
15) In the _first_ browser click "Start Game"
16) Confirm that you do not go to the 1st question screen in either browser
17) In the _first_ browser, confirm that you see an alert box displayed as a result of calling the alert() function telling you to pick a round number and click "OK"
18) Go to http://minorprophets.tech/ in a different browser to simulate a third player
12) Use username: "testrun1" and  password: "Testrun1!" as login credentials
13) Click "Login"
14) Enter roomcode and click "Join Game"
15) In the _first_ browser click "Start Game"
16) Confirm that you do not go to the 1st question screen in any of the browsers
17) In the _first_ browser, confirm that you see an alert box displayed as a result of calling the alert() function telling you to pick a round number and click "OK"
18) In the _first_ browser, select "4" for the number of rounds
19) In the _first_ browser, select "3" for the number of rounds
20) In the _first_ browser, select "5" for the number of rounds
21) In the _first_ browser, click "Start Game" 
22) Confirm that the question screen says Round 1 out of 5 in the element with id "rounds" in all browsers
23) Confirm that a question is displayed with 4 choices in all browsers
24) Click "Quit"
25) Repeat steps 4-24 5 times

**Comment by ProfMatthewHz** [comment]
As before, please be more specific in these tests. Explain what the limits in rounds are. Also, here is where you should have the test that verifies you can select a proper number of rounds after trying (and failing) to leave the number of rounds blank.

There are actually other steps needed for this to work that are not included here. What database table & field is used to hold the number of rounds being played? Which one is reset at the start of the game and in which the current round is tracked? These are important details that would allow work to be done in parallel.
