### ISSUE TITLE
As a consistent player, I would like to view my profile so that I can see my statistics which include number of games, number of questions correct, and number of wins.

### ISSUE THREAD

**Issue by HarrisonHutton** [samarthjj/CSE-442-Group-Project#6]
**Acceptance Tests:**

*Test 1 - New Player*
1) Go to http://minorprophets.tech/ 
2) Under the "Sign Up" text (below "Login"), Enter a new unique username, such as `newuser123`
3) Enter `Apple123*` as the Password in both Password fields
4) Click the "Sign Up" button below the Password field
5) Click the "Profile" button in the top left corner
6) Confirm this new account has "Number of Games: 0", "Number of Questions Correct: 0" and "Number of Wins: 0."

--- 

*Test 2 - Veteran Player*
1) Go to http://minorprophets.tech/
2) Under the "Login" text, enter `veteranuser` as the Username and `Apple123*` as the Password
3) Click the "Login" button
4) Click the "Profile" button in the top left corner
5) Confirm this account has "Number of Games Played: 3", "Number of Questions Correct: 2", and "Number of Wins: 2" to showcase the functionality of saving statistics.

**Comment by ProfMatthewHz** [comment]
** Be specific in your tests** Give me exact numbers for the results and not simply state "values greater than 0". Since the data are made up, make them up. If needed, create a test account that is not used in any other test.
