### ISSUE TITLE
Add ability for players to view their saved statistics

### ISSUE THREAD

**Issue by joshcaskie** [samarthjj/CSE-442-Group-Project#60]
PostgreSQL table **accounts** used. 
Columns and usages:
* **games_won** --> Number of wins (when the player reaches the Game Over screen)
*  **total_points** --> Number of questions correct (whenever the scores are calculated for a player)
* **ratio** --> Number of games started/played (when a game is started with that player in the lobby)
--- 

*Test 1 - New Player*
1) Go to the site (either http://minorprophets.tech/ or locally deployed site home page)
2) Under the "Sign Up" text (below "Login"), Enter a new unique username, such as `tasktestnewplayer1`, or another option
3) Enter `Apple123*` as the Password in both Password fields
4) Click the "Sign Up" button below the Password field
5) Click the "Profile" button in the top left corner
6) Confirm this new account has "Number of Games: 0", "Number of Questions Correct: 0" and "Number of Wins: 0."
7) Confirm these statistics are saved in the database in the backend by following steps 3a to 3g in Test 2, but with the chosen username for the SQL query and that the statistics are all 0.

--- 

*Test 2 - Veteran Player*
1) Go to the site (either http://minorprophets.tech/ or locally deployed site home page)
2) Under the "Login" text, enter `veteranuser` as the Username and `Apple123*` as the Password
3) Click the "Login" button
3a) **Confirm the database has stored values for `veteranuser`**
3b) Go to https://dashboard.heroku.com/apps/minor-prophets (and log in with private credentials for access if necessary)\
3c) Under the "Overview" tab, for the "Installed add-ons" click on "Heroku Postgres" to be taken to another page
3d) Click the "Dataclips" tab
3e) Click the "View \`veteranuser\` Info" dataclip
3f) Confirm the command is `SELECT games_won, total_points, ratio FROM accounts WHERE username = 'veteranuser';`
3g) Confirm the columns have these values: games_won = 2, total_points = 2, and ratio = 3.
4) **(Back on minorprophets.tech)** Click the "Profile" button in the top left corner
5) Confirm this account has "Number of Games: 3", "Number of Questions Correct: 2", and "Number of Wins: 2".

---

*Test 3 - Confirm that new stats are saved as someone plays a game*
1) Go to the site (either http://minorprophets.tech/ or locally deployed site home page)
2) Under the "Login" text, enter `newstatsperson` as the Username and `Apple123*` as the Password
3) Click the "Login" button
4) Click the "Profile" button
5) Record the current Profile statistics and values before a new game is recorded
6) Click the "Back" button
7) Click "Start New Game" (will change once rounds are added as a requirement). This will increment the number of games a player has played (even if the game isn't finished) in their statistics.
8) Click "Start Game" in the top right after confirming the player appears in the "Players" box. (This may require some refreshes for now as it seems there are some other bugs with loading into the lobby. A Flask server restart might also be warranted depending on the severity of the condition.). 
8) Click one of the answer choices on the left.
9) Click "Countdown Done"
10) Click "Reveal Answer" (will change once the timer is implemented)
11) Click "Calculate Scores"
12) Click "Get Scores"
13) Confirm the answer is either correct or incorrect, and the score was incremented accordingly This will update the player's number of questions correct for their statistics.
14) Click "New Question"
15) Repeat steps 9-15 until the question displays the text "Game Over" (will change once the timer/# of rounds is implemented)
16) Click "Countdown Done" again
17) Click "Game Over" to finish the game. This will update the game score and calculate the Winner of the game to increment the winner's statistic. If the players in the lobby do not reach the Game Over screen, no winner is calculated.
18) Click "Exit"
19) Click "Profile" and confirm the statistics are updated according to the game that was played.  The player should have seen their Number of Wins increase by 1, Number of Games Played increase by 1, and Number of Questions Correct increase by anywhere from 0 to 3 (default games are 3 questions each). 
20) Confirm these statistics are saved in the database in the backend by following steps 3a to 3g in Test 2, but with the chosen username for the SQL query (`newstatsperson`) and that the statistics are all that we've seen throughout the application interaction.

**Comment by ProfMatthewHz** [comment]
**This needs to be added as a dependency of the user story ASAP**

Test 2 seems backwards. Normally we check the database (possibly adding data to the database) and then verify that the display is correct. What table and columns are being used? Adding those details guarantees that everyone is updating the correct information during game play.
