### ISSUE TITLE
Add text-messaging/emoji support to messaging service.

### ISSUE THREAD

**Issue by samarthjj** [samarthjj/CSE-442-Group-Project#61]
**Task Tests**

*Test 1 - Text-messaging - Sender*
<ol>
<li>Go to http://minorprophets.tech/ </li>
<li>Login using the username `zenhub1`.</li>
<li>Enter `Apple123*` as the Password.</li>
<li>Click the "Login" button.</li>
<li>Click the "Start New Game" button.</li>
<li>Click the "Start Game" button.</li>
<li>On the right hand side of the screen you will see a messenger labelled "Messages", use that space to send messages.</li>
<li>Type in a message of your choice.</li>
<li>Hit the "Enter" button on your keyboard.</li>
<li>Confirm that your message was sent and appears in the Messages.</li>
</ol>

---

*Test 2 - Emojis - Sender*
<ol>
<li>Go to http://minorprophets.tech/ </li>
<li>Login using the username `zenhub1`.</li>
<li>Enter `Apple123*` as the Password.</li>
<li>Click the "Login" button.</li>
<li>Click the "Start New Game" button.</li>
<li>Click the "Start Game" button.</li>
<li>On the right hand side of the screen you will see a messenger labelled "Messages", use that space to send messages.</li>
<li>Type in a message of your choice, comprising on emoticons, which can be chosen by clicking on the smiley face on the right side of the input.</li>
<li>Hit the "Enter" button on your keyboard.</li>
<li>Confirm that your message, with emojis, was sent and appears in the Messages.</li>
</ol>

---

*Test 3 - Receiver*
<ol>
<li>Follow steps 1-5 from <b>Test 1</b>, this acts as the sender.</li>
<li>Follow steps 1-4 from <b>Test 1</b> in a different browser or incognito/private browsing mode, this will be our receiver.</li>
Sender - 
<li>Share the room code, obtained at step 5 in <b>Test 1</b>, with the receiver.</li>
Receiver -
<li>Paste the room code into the field above the "Join Game" button.</li>
<li>Click on the join game button.</li>
Sender -
<li>Click the "Start Game" button.</li>
<li>Enter a text message of you choice.</li>
<li>Click the "Send" button.</li>
Receiver -
<li>Confirm that you received the sent message and it is displayed on your screen.</li>
</ol>

**Comment by ProfMatthewHz** [comment]
@samarthjj What happens if a message is blank?  
What happens if a message contains a mix of emoticons and text?  
What happens if a paste in Arabic text (or another language written left-to-right) and then start typing?  
(The last test is not needed for 442, but is ABSOLUTELY needed in the real world. You would also need tests of very long messages to see if there are limits.)
