### ISSUE TITLE
Add quick reactions to messaging service.

### ISSUE THREAD

**Issue by samarthjj** [samarthjj/CSE-442-Group-Project#63]
**Task Tests**

*Test 1 - 👍*
<ol>
<li>Go to http://minorprophets.tech/ </li>
<li>Login using the username `zenhub1`.</li>
<li>Enter `Apple123*` as the Password.</li>
<li>Click the "Login" button.</li>
<li>Click the "Start New Game" button.</li>
<li>Click the "Start Game" button.</li>
<li>Confirm that you see quick reaction for "👍".</li>
<li>Confirm that upon clicking the quick reaction for 👍, a message is sent on your behalf with the structure, "zenhub1: 👍".</li>
</ol>

---

*Test 2 - 👎*
<ol>
<li>Go to http://minorprophets.tech/ </li>
<li>Login using the username `zenhub1`.</li>
<li>Enter `Apple123*` as the Password.</li>
<li>Click the "Login" button.</li>
<li>Click the "Start New Game" button.</li>
<li>Click the "Start Game" button.</li>
<li>Confirm that you see quick reaction for "👎".</li>
<li>Confirm that upon clicking the quick reaction for 👎, a message is sent on your behalf with the structure, "zenhub1: 👎".</li>
</ol>

---

*Test 3 - 👏*
<ol>
<li>Go to http://minorprophets.tech/ </li>
<li>Login using the username `zenhub1`.</li>
<li>Enter `Apple123*` as the Password.</li>
<li>Click the "Login" button.</li>
<li>Click the "Start New Game" button.</li>
<li>Click the "Start Game" button.</li>
<li>Confirm that you see quick reaction for "👏".</li>
<li>Confirm that upon clicking the quick reaction for 👏, a message is sent on your behalf with the structure, "zenhub1: 👏".</li>
</ol>

---

*Test 4 - Receiver*
<ol>
<li>Follow steps 1-5 from <b>Test 1</b>, this acts as the sender.</li>
<li>Follow steps 1-4 from <b>Test 1</b> in a different browser or incognito/private browsing mode, this will be our receiver.</li>
Sender - 
<li>Share the room code, obtained at step 5 in <b>Test 1</b>, with the receiver.</li>
Receiver -
<li>Paste the room code into the field above the "Join Game" button.</li>
<li>Click on the join game button.</li>
Sender -
<li>Click the "Start Game" button.</li>
<li>Enter a text message of you choice.</li>
<li>Hit the Enter button on your keyboard.</li>
Receiver -
<li>Confirm that you received the sender's quick reaction and it is displayed on your screen.</li>
</ol>

**Comment by ProfMatthewHz** [comment]
Test 1
   - With the structure, ": " ... and? Is there more to this or are all 3 sent the same way?

Test 2
   - There are 3 different quick reactions. That is not an exhaustive number. Please write one test per reaction.
