### ISSUE TITLE
As the room owner I want to choose the number of rounds to play so that all players can see which round we are in as we play the game

### ISSUE THREAD

**Issue by joshcaskie** [samarthjj/CSE-442-Group-Project#8]
**Acceptance Tests**

*Test 1* (Every button)
1) Go to http://minorprophets.tech/ or run the app locally
2) Enter your username or "zenhub1" if you don't have an account
3) Enter your password or "Apple123\*" if you don't have an account
4) Click "Login"
5) Click "Start New Game"
6) Confirm that you see 5 buttons to select for the number of rounds: 1, 2, 3, 4, and 5
7) In this step, select one of the buttons, the first time, select "1", then the next time "2" and so on, until all buttons have been tested 
8) Confirm that the button you selected is highlighted
9) Click "Start Game"
10) Confirm that the question screen says Round 1 out of however many rounds you selected in Step 7
11) Select an answer and press "Countdown Done"
12) Confirm that the answer screen says Round 1 out of however many rounds you selected in Step 7
13) Click "Quit"
14) Repeat steps 5-13 4 more times, choosing a new round button each time

*Test 2* (Current round increments) 
1) Go to http://minorprophets.tech/ or run the app locally
2) Enter your username or "zenhub1" if you don't have an account
3) Enter your password or "Apple123\*" if you don't have an account
4) Click "Login"
5) Click Start New Game
6) Select "3" for the number of rounds 
7) Confirm that the "3" button is highlighted
8) Click "Start Game"
9) Confirm that the question screen says Round 1 out of 3
10) Select an answer and press "Countdown Done"
11) Confirm that the answer screen says Round 1 out of 3
12) Click "Reveal Answer"
13) Click "New Question"
14) Repeat steps 9-13 2 more times
15) Confirm that the question screen says Round 2 out of 3
16) Select an answer and press "Countdown Done"
17) Confirm that the answer screen says Round 2 out of 3
18) Click "Reveal Answer"
19) Click "New Question"
20) Repeat steps 15-19 2 more times
21) Confirm that the question screen says Round 3 out of 3
22) Select an answer and press "Countdown Done"
23) Confirm that the answer screen says Round 3 out of 3

*Test 3* (Change # of rounds selected)
1) Go to http://minorprophets.tech/ or run the app locally
2) Enter your username or "zenhub1" if you don't have an account
3) Enter your password or "Apple123\*" if you don't have an account
4) Click "Login"
5) Click Start New Game
6) Select "1" for the number of rounds
7) Now select "2" for the number of rounds 
8) Confirm that the "2" button is highlighted
9) Click "Start Game"
10) Confirm that the question screen says Round 1 out of 2
11) Select an answer and press "Countdown Done"
12) Confirm that the answer screen says Round 1 out of 2

*Test 4* (None selected causes error, then pick a number)
1) Go to http://minorprophets.tech/ or run the app locally
2) Enter your username or "zenhub1" if you don't have an account
3) Enter your password or "Apple123\*" if you don't have an account
4) Click "Login"
5) Click "Start New Game"
6) Do not select the number of rounds
7) Confirm that none of the round number choices are highlighted
8) Click "Start Game"
9) Confirm that you do not go to the 1st question screen
10) Confirm that you see an alert telling you to pick a round number and click "OK"
11) Select "2" for the number of rounds 
12) Click "Start Game" again
13) Confirm that you now go to the question screen, and that it says Round 1 out of 2

**Comment by ProfMatthewHz** [comment]
**Be specific in your tests** Explicitly state what the number of rounds should be entered and then use this number everywhere. Can the user enter 0? What about 10000000? If not, how is this limited? If that is done via a dropdown, include a test expressing what values are supposed to be in the dropdown. If not include more tests showing the different possible errors.

I will be honest: do not worry about the second user **in your acceptance tests**. (But absolutely test for this in your task tests.) As a user, I assume that if I select 3 rounds and am only allowed to play 3 rounds then other people in the room also get 3 rounds. Eliminate those as acceptance tests (but keep them as task tests).
